name: tox demo

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8 # tox で指定したpythonに合わせる

            - name: Install tox
              run: pip install tox

            - name: Run tox
              run: tox